### ISSUE TITLE
Update to Electron 14

### ISSUE THREAD

**Issue by lefterisgar** [lefterisgar/caprine#6]
The official Caprine ships with Electron 10 and with some patches here and there I have managed to bump it up to Electron 13 which solves a serious bug some users (myself included) were having.

As Electron 13 has been deprecated, there is an urgent need to move away from it because it poses a significant security risk. Also, this would likely solve a few bugs, including #5.

What's keeping me from bumping the Electron version, is the `enableRemoteModule` option which has been separated from Electron.

@1nikolas if you have any spare time, please prioritize this over the other issues you have mentioned

**Comment by 1nikolas** [comment]
Okay so after a lot of research I found where the problem is.
First of all, electron 14 requires us to use the `@electron/remote` module instead of the electron.remote (hence the `enableRemoteModule` error). Remote isn't used much on the app, only on the [electron-util](https://github.com/sindresorhus/electron-util) module which is made by the creator of Caprine. The problem with this module is that it doesn't support the `@electron/remote` module (so it doesn't support electron >=14) and there is no plan to support it (as seen [here](https://github.com/sindresorhus/electron-util/issues/45) and [here](https://github.com/sindresorhus/electron-util/pull/37)). So we need to find alternatives

**Comment by 1nikolas** [comment]
Also we have to say goodbye to the `do-not-disturb` module which manages do not disturb on mac (uses electron-util)

**Comment by lefterisgar** [comment]
@1nikolas Thank you so much for your interest in moving this project forward!
I think that creating (or adapting) an electron-util alternative is too much work. What about forking electron-util and then applying some patches to make it compatible?
Right now there is an [open PR](https://github.com/sindresorhus/electron-util/pull/58) which removes the remote module and bumps electron to v19.
The do-not-disturb module doesn't really matter right now because I can't even build for macOS :(

**Comment by 1nikolas** [comment]
> The do-not-disturb module doesn't really matter right now because I can't even build for macOS :(

I can do mac builds with a (100% legitimate & legal) MacOS vm


> I think that creating (or adapting) an electron-util alternative is too much work. What about forking electron-util and then applying some patches to make it compatible?

I did some tests yesterday and at this point I'm not 100% sure if electron-util is even the problem. Most of the utils caprine uses don't use remote and even after removing these I get to the same error: `can't preload browser.js`. Something in `browser.js` still uses remote and I can't find what it is.. Because if I enable remote on the current electron version it works just fine. If I use remote with the new way (with the remote module) it doesn't work because whatever uses remote it uses it the old way.. And the preload error doesn't help (doesn't tell where the error is)

**Comment by lefterisgar** [comment]
> I can do mac builds with a (100% legitimate & legal) MacOS vm. Jokes aside the legal way to go here is to use [Darling](https://www.darlinghq.org/) on Linux but I have no idea if this can run node.
Oh, that's great!

> I did some tests yesterday and at this point I'm not 100% sure if electron-util is even the problem. Most of the utils caprine uses don't use remote and even after removing these I get to the same error: `can't preload browser.js`. Something in `browser.js` still uses remote and I can't find what it is.. Because if I enable remote on the current electron version it works just fine. If I use remote with the new way (with the remote module) it doesn't work because whatever uses remote it uses it the old way.. And the preload error doesn't help (doesn't tell where the error is)
Are you testing on Electron 14? Because I have heard that remote was removed totally in Electron 15? I am not sure though. If only you were able to eventually work it out... that would be a blessing!

**Comment by 1nikolas** [comment]
I managed to run it successfully (yay) but I had to remove a ton of stuff. I think I know where the problem is now. It's the `electron-is-dev` module which is being used constantly buy the modules sindresorhus has made (namely `do-not-disturb`, `electron-context-menu`, `electron-debug` and `electron-util`). And the problem is that this module is being used in a 2 depth dependency situation (aka dependency of a dependency) which means the only way is to re-inppument. I mean most modules are being used once so it should be easy to copy the non-problematic code

**Comment by 1nikolas** [comment]
sindresorhus's module ecosystem makes sense since he's making lots of apps which use them but it's very frustrating to deal with when one of them breaks..

**Comment by 1nikolas** [comment]
`electron-is-dev` is indeed the cause of the problem. I manually edited the module files from `node_modules` and it works perfectly fine. If only there was a hacky way we can replace module files after `npm i`..

**Comment by lefterisgar** [comment]
Wow, I'm really amazed by your work! I'm going to test and merge everything and then do a reevaluation to see if everything functions correctly. I honestly don't know how to thank you!

**Comment by 1nikolas** [comment]
> Wow, I'm really amazed by your work! I'm going to test and merge everything and then do a reevaluation to see if everything functions correctly. I honestly don't know how to thank you!

You might wanna hold up releasing a new update, I'm going update some broken class names here and there and fix some stuff for the new messenger ui (which strangely appears only on my main fb account, tried a secondary account still has the "old" one; I guess it's good to have access to both for testing). Also wanted to implument an update notification (I think the updater from the original repo broke like some years ago) anyway it's really easy to do

I always wanted to fix this broken hell of an app which caprine has been lately and now that I got some free time i think it's the time to do it

**Comment by lefterisgar** [comment]
Okay then, I'm going to create a separate branch for it in the meantime. I think it's great to see someone interested in fixing that project. It's a total mess as you have said because nobody has really maintained it for the past two years.

In order to make your life easier I have invited you to become a collaborator so you don't need to open pull requests in the future. We could also make a testing branch when we want to release a stable version. Also if you think that the versioning should not depend on the upstream project feel free to make any suggestions!

**Comment by lefterisgar** [comment]
You are really lucky to have two accounts with both layouts! Of all my 5 accounts none has the new layout!
