### ISSUE TITLE
login address hijacked

### ISSUE THREAD

**Issue by rosoau** [lefterisgar/caprine#7]
I leave the keep me signed in unchecked.
Recently I added a friend via the Facebook webpage
When I opened Caprine it had his Facebook login address
in my login window. 
My friend had already set up caprine with his credentials previously
but yesterday when he started Caprine it had my login address
in his login window
Is there some foul joke or hack at work; what's going on here? 
Isn't my login address stored in a file in ~/.config/Caprine/
and if so how can that be changed without me knowing?

**Comment by lefterisgar** [comment]
Hi @rosoau! I'm currently unaware of any security incident regarding authentication. Something might have gone wrong at work, as you said. Maybe deleting ~/.config/Caprine/ and starting out fresh could help. If you think you have found a potential security compromise, I would suggest you to report the issue upstream so it reaches more people.

**Comment by rosoau** [comment]
Thanks for prompt reply. Which is upstream? sindrehus? this issue has to be known to the developers. I don't know if it is a security because I don't keep signed in and so my password is not stored locally. But just this weird interaction of the browser doings with caprine needs attention.

**Comment by lefterisgar** [comment]
Yeah. Upstream is [sindresorhus/caprine](https://github.com/sindresorhus/caprine). You are here because at some point you have probably downloaded my fork.

Unfortunately Sindre, project's author, said that the project has now entered "Maintenance mode" which means no new features and only bugfixes. Judging by the commit history in the past few months, activity has stalled. In short, let the main devs know but let me tell you: Caprine has a loooot of security issues (that won't be fixed) and what you found might just be the tip of the iceberg.

**Comment by lefterisgar** [comment]
Closing this as upstream-related.
